apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "comp-b.fullname" . }}
  labels:
    {{- include "comp-b.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "comp-b.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "comp-b.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "comp-b.fullname" . }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
