# Default values for comp-b.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

deployprefix: "p123123-"

image:
  repository: ghcr.io/idevopsdemo/comp-b
  pullPolicy: Always
  tag: latest

imagePullSecrets: []
  # - name: regcred

env:
  DATACOLLECTOR_STORAGE: "mysql"
  QCLIENT_BROKER_HOST: "mosquitto"
  STORAGE_MYSQL_HOST: "mysql"
  STORAGE_MYSQL_DB: "xo-sample"

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
